default_agent: vega_underwriting_agent
agents:
  vega_underwriting_agent:
    name: vega_underwriting_agent
    language: python
    node_version: '20'
    entrypoint: D:/project-vega/coaction_agent_platform/app/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: D:\project-vega
    aws:
      execution_role: arn:aws:iam::513847850768:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-73b013ba7f
      execution_role_auto_create: false
      account: '513847850768'
      region: us-east-1
      ecr_repository: 513847850768.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-vega_underwriting_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: vega_underwriting_agent-grSg5rFgUu
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:513847850768:runtime/vega_underwriting_agent-grSg5rFgUu
      agent_session_id: 9ec1f1d5-7187-4ac5-a1ca-989920e284fb
    codebuild:
      project_name: bedrock-agentcore-vega_underwriting_agent-builder
      execution_role: arn:aws:iam::513847850768:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-73b013ba7f
      source_bucket: bedrock-agentcore-codebuild-sources-513847850768-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: vega_binding_authority_bot_memory-NhScy1585h
      memory_arn: null
      memory_name: vega_underwriting_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration:
      requestHeaderAllowlist:
      - X-Amzn-Bedrock-AgentCore-Runtime-Custom-Authorization
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
